import type { StoredIntentPack } from "./types.js";

function renderChecklist(items: string[]): string {
  return items.map((item) => `- [ ] ${item}`).join("\n");
}

function renderBullets(items: string[]): string {
  return items.map((item) => `- ${item}`).join("\n");
}

/**
 * Generates a structured PR description template from a saved Intent Pack.
 * The output is markdown, ready to paste into a GitHub PR description.
 */
export function toPrDescription(pack: StoredIntentPack): string {
  const lines: string[] = [];

  // Title hint
  lines.push(`## ${pack.goal ?? pack.objective}`);
  lines.push("");

  // Resolves line (placeholder if no prLink)
  lines.push(`> Resolves: <!-- paste issue URL here -->`);
  lines.push("");

  lines.push("## What this PR does");
  lines.push(pack.objective);
  lines.push("");

  if (pack.repositoryContext) {
    lines.push("## Repository context");
    lines.push(pack.repositoryContext);
    lines.push("");
  }

  lines.push("## Acceptance criteria");
  lines.push(renderChecklist(pack.acceptanceCriteria));
  lines.push("");

  lines.push("## Files / areas touched");
  lines.push(renderBullets(pack.touchedAreas));
  lines.push("");

  lines.push("## Constraints respected");
  lines.push(renderBullets(pack.constraints));
  lines.push("");

  if (pack.nonGoals.length > 0) {
    lines.push("## Non-goals (not in scope)");
    lines.push(renderBullets(pack.nonGoals));
    lines.push("");
  }

  if (pack.risks.length > 0) {
    lines.push("## Risks considered");
    lines.push(renderBullets(pack.risks));
    lines.push("");
  }

  if (pack.openQuestions.length > 0) {
    lines.push("## Open questions");
    lines.push(renderBullets(pack.openQuestions));
    lines.push("");
  }

  if (pack.notes && pack.notes.trim()) {
    lines.push("## Notes");
    lines.push(pack.notes.trim());
    lines.push("");
  }

  lines.push("---");
  lines.push(`_Generated by Ghostrail — Intent Pack \`${pack.id}\`_`);

  return lines.join("\n");
}
